base_images:
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  project_image:
    dockerfile_path: ci/Dockerfile
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: sanity
  commands: SANITY_TEST_ARGS='--venv' make test-sanity
  container:
    from: root
- as: integration
  commands: make test-integration
  openshift_installer_src:
    cluster_profile: aws
zz_generated_metadata:
  branch: main
  org: ansible-collections
  repo: community.okd
